### ISSUE TITLE
Set up project 

### ISSUE THREAD

**Issue by zyuiop** [Susanfe/sdp-event-management#1]
Create, link to codeclimate and travis

**Comment by Fnux** [comment]
@Luminilion you should have splitted the "initial commit" (6616cc47ca0a6b41b01149b81981f86afe21a0a5) into multiples ones: we want to start from the initial project and easily see what was changed.

I would like to fix that while there is still nothing useful on the repo and split the commit into "Initial AndroidStudio project" and "Enable Travis CI and CodeClimate". What do you think?

**Comment by Luminilion** [comment]
Yes split it !

**Comment by Fnux** [comment]
It's still your issue. I can do it but I think it's better if you fix it yourself:
  * Delete the current branch: `git update-ref -d HEAD` (it's the only commit of your only branch, you can't use things like `git branch -D`. You should not have to reuse this command anytime).
  * Add and commit the initial AndroidStudio project: `git add app/ grad* settings.gradle build.gradle .gitignore; git commit -m "Initial AndroidStudio project"`
  * Add and commit the travis configuration: `git add .travis.yml; git commit -m "Import Travis CI configuration"`
  * Add and commit the codeclimate configuration: `git add .travis.yml; git commit -m "Enable the CheckStyle and SonarJava Codeclimate plugins"`
  * Unprotect the master branch in the repository's settings
  * Override the remote master with `git push --force origin master`
  * Re-protect the master branch in the repostory's settings

:-)

**Comment by Luminilion** [comment]
The probleme now is that I can't do that anymore as there are 2 branches, so I can either delete all the files in the main and then re add them as you meant (which will trigger lots of commits following a strange behavior) or we just consider the inital commit in its globality from now on.

Moreover we didn't setup Travis and CodeClimate correctly so I am working on it and thus waiting for @zyuiop to let Travis consider the Susanfe organization.

**Comment by Fnux** [comment]
We can rebuilt master and cherry-pick the commit you applied to the the original tree. I don't think we need an organization: I properly configured Codeclimate and Travis CI on a personnal repository for the bootcamp.

Do you want me to take over this issue?

**Comment by Luminilion** [comment]
Rebuilding master and cherry-picking commit is what I imagined (even though I don't know yet how to do it so you can take over if you think it will be too long for me to find how to do that).
I also properly configured everything for the bootcamp but the bootcamp is your repo, while the sdp-event-management is not and thus this is a problem because it is not listed in your repos...
This is why I asked for it to become an organization, so that I can request access to it from my Travis and CodeClimate accounts.
I plan on adding the README with all the badges at the end.

**Comment by Fnux** [comment]
I'll rebuild master this afternoon, we'll discuss it next time we meet.

**Comment by Fnux** [comment]
I moved the 'old' branches to `master-old` and `fb-event-old`. The "initial commit" is now properly split and rebase the `fb-event` branch (see #3) against the new master.

**Comment by zyuiop** [comment]
Could you please remove the default provided tests so that all the tests pass and the build passes? Can you do this ASAP as we need all tests to pass on master by wednesday at noon? Thanks :)

**Comment by zyuiop** [comment]
Seems okay for me, good job
