### ISSUE TITLE
As a user I can select some items in the schedule and mark them in order to add them to "my schedule"

### ISSUE THREAD

**Issue by zyuiop** [Susanfe/sdp-event-management#10]

**Comment by antoine-crettenand** [comment]
TODO list

- [x] Each ScheduleActivity has a unique id
- [x] Provide basic interface to add ScheduleActivity to the db
- [x] Press long enough on an activity in the ScheduleActivity View to add it to the DB
- [x] Implement a MyScheduleActivity View which retrieves every JoinedScheduleActivity from the db and displays them
