### ISSUE TITLE
Set every findViewById with @Bind

### ISSUE THREAD

**Issue by Luminilion** [Susanfe/sdp-event-management#147]

**Comment by zyuiop** [comment]
Should not be in the backlog

**Comment by Luminilion** [comment]
I didn't know where to put it, where should it go ?

**Comment by zyuiop** [comment]
It should just be an issue, but not be in the scrum board I think?

**Comment by Luminilion** [comment]
I don't know but for me I never look at the issues, the scrum board is my
to do list buy move it if necessary
