### ISSUE TITLE
As an user, I can see the location of my friends on the map

### ISSUE THREAD

**Issue by zyuiop** [Susanfe/sdp-event-management#19]

**Comment by Fnux** [comment]
I don't think we need an "account" concept for the visitors: perhaps we can link them using short UUID generated at will? I'd like to keep the authentication for event organizer only.

**Comment by Luminilion** [comment]
I agree with that it will simplify everything at first! 
We can complexity at the end of really necessary.

**Comment by Fnux** [comment]
See #38.
