### ISSUE TITLE
As an authenticated user, I can see my event tickets if I have bought them from a compatible platform

### ISSUE THREAD

**Issue by zyuiop** [Susanfe/sdp-event-management#23]

**Comment by Fnux** [comment]
We might want to support [polyticket](https://polyticket.agepoly.ch/), but I don't know where to find the documentation (perhaps on Polylan's gitlab instance?). @zyuiop

**Comment by zyuiop** [comment]
As the user doesn't log in at all, he would have to log in against some backends to access his tickets, which is way too cumbersome for the feature to be useful. Cancelled.
