### ISSUE TITLE
As an event staff, I can scan tickets and check them agains compatible backends

### ISSUE THREAD

**Issue by zyuiop** [Susanfe/sdp-event-management#25]
The idea is to support one or two interesting backends, and define an api the organizer can implement on his side

**Comment by zyuiop** [comment]
In sprint 6: try to implement the check against [ji-shop](https://github.com/PolyJapan/ji-shop) (it will be used as the reference API)
In next sprints (maybe): add other backends

**Comment by zyuiop** [comment]
Reference for the ji-shop backend:

`POST           /users/login`
Request: `{email: ..., password: ...}`
Reply: `{success: true|false, errors: [], token?: auth token}`

**Comment by Luminilion** [comment]
I think we should definitely think more about the ticket's backend, because if no other backend is planned to be integrated, it is useless to implement **only** the JapanImpact backend for the global use of the app.
Are other ticket backends going to be integrated ?

**Comment by zyuiop** [comment]
The idea is that we only check agains JI's backend, and the event admin can
then change the URL of it's backend, so he can build his own backend, he
just need to make sure the backend is compatible.

Le mer. 31 oct. 2018 à 15:45, Luminilion <notifications@github.com> a
écrit :

**Comment by Luminilion** [comment]
Ok that works for me if it is a simple uri change, is it only that ?

**Comment by zyuiop** [comment]
Yep, I was about to finish describing the way this API works but I had to
do something else.
Basically there is one endpoint to login and an endpoint to check a ticket,
that must return some data to indicate if it's good or not.

Le mer. 31 oct. 2018 à 22:08, Luminilion <notifications@github.com> a
écrit :
