### ISSUE TITLE
Think on what requires authentication

### ISSUE THREAD

**Issue by Fnux** [Susanfe/sdp-event-management#38]
I'd like to keep the authentication for event organizer only: we have to think on what can be done to avoid it for the visitor.

**Comment by Luminilion** [comment]
I think we need to focus on these points :
What info needs to be retained about the visitor ?
Friends ? Ticket ? Personnal Schedule ? Pinned News ?

Do we differenciate the visitor visiting and the visitor who bought a ticket ?

Does the organizer have the rights to set event properties (description, location, news ...) ? If No, what differentiates him from the user ?
