### ISSUE TITLE
Can we drop compatibility with older android API revisions?

### ISSUE THREAD

**Issue by Fnux** [Susanfe/sdp-event-management#42]
Keeping compatibility with API level 15 is a pain, can we rise the lowset supported version to 24? I discussed with a member of another group who got the approval of their TA.

**Comment by Luminilion** [comment]
@betty needs to approve I think, but personnaly I really approve this modifcation.

**Comment by betty** [comment]
np; the only thing - make it work with Travis

**Comment by Fnux** [comment]
I'll try to make it work on a separate branch.

**Comment by zyuiop** [comment]
Fixed

**Comment by Fnux** [comment]
Not so fast! Due to complication with the tests on Travis, we had to revert the change.
