### ISSUE TITLE
EventActivity - Fix event description

### ISSUE THREAD

**Issue by Luminilion** [Susanfe/sdp-event-management#49]
When the EventAcitivty is reached from the EventSelector screen, the description loads perfectly.
 But when the user comes from another activity (such as ScheduleActivity) the description is not loaded.

**Comment by zyuiop** [comment]
#50 is a duplicate.

**Comment by zyuiop** [comment]
More specifically, the event ID is not passed in the intent (there is no intent at all) and it's not kept by the activity, so it's just lost. 

Maybe the viewmodel isn't, so we should try to see what we can do with it.

**Comment by Fnux** [comment]
Fixed by #60, now merged in master. Closing.
