### ISSUE TITLE
Make the EventShowcase a multi-fragment activity

### ISSUE THREAD

**Issue by zyuiop** [Susanfe/sdp-event-management#51]
We should make each part a fragment of the same activity, to avoid the need to pass the event id between activities, and to share the Event when available.

We should also put a lateral menu as an other fragment.

This would probably fix #50

**Comment by Luminilion** [comment]
What do you mean by each part ?
What would lateral menu bring ?

**Comment by zyuiop** [comment]
Lateral menu would allow the user to navigate from any activity, and not only from the main activity of the event

**Comment by Fnux** [comment]
Merged in master. We still have to convert the schedule and map activities to fragments.
